# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Forge

class DataType(object):
    Bool = 0
    Uint8 = 1
    Uint16 = 2
    Uint32 = 3
    Uint64 = 4
    Int8 = 5
    Int16 = 6
    Int32 = 7
    Int64 = 8
    Fp16 = 9
    Fp32 = 10
    Fp64 = 11
    String = 12

